### ISSUE TITLE
Completion not working with IPython v3.2.1

### ISSUE THREAD

**Issue by smutch** [ivanov/vim-ipython#134]
Completion with
- IPython==3.2.1
- vim-ipython==latest
- pyzmq==14.7.0
- Python==2.7.2

seems to be broken:

```
Error detected while processing function CompleteIPython:
line   40:
Traceback (most recent call last):
Error detected while processing function CompleteIPython:
line   40:
  File "<string>", line 3, in <module>
Error detected while processing function CompleteIPython:
line   40:
  File "/mnt/home/smutch/.vim/plugged/vim-ipython/ftplugin/python/vim_ipython.py", line 323, in ipy_compl
ete
Error detected while processing function CompleteIPython:
line   40:
    msg_id = kc.shell_channel.complete(base, current_line,
Error detected while processing function CompleteIPython:
line   40:
AttributeError: 'ZMQSocketChannel' object has no attribute 'complete'
Error detected while processing function CompleteIPython:
line   40:
Traceback (most recent call last):
Error detected while processing function CompleteIPython:
line   40:
  File "<string>", line 3, in <module>
Error detected while processing function CompleteIPython:
line   40:
  File "/mnt/home/smutch/.vim/plugged/vim-ipython/ftplugin/python/vim_ipython.py", line 323, in ipy_compl
ete
Error detected while processing function CompleteIPython:
line   40:
    msg_id = kc.shell_channel.complete(base, current_line,
Error detected while processing function CompleteIPython:
line   40:
AttributeError: 'ZMQSocketChannel' object has no attribute 'complete'
```
